name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: "2.2.10"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release
        run: |
          nimble release -y

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # Points to the binary inside the bin folder
          files: |
            bin/nsstats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
